---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jsonserver-operator
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.example.com
  resources:
  - jsonservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.example.com
  resources:
  - jsonservers/finalizers
  verbs:
  - update
- apiGroups:
  - example.example.com
  resources:
  - jsonservers/status
  verbs:
  - get
  - patch
  - update
