name: Build and Push to ttl.sh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Generate image tag
        id: tag
        run: |
          SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=ttl.sh/jsonserver-operator-${SHA_SHORT}:24h" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          push: true
          tags: ${{ steps.tag.outputs.IMAGE_TAG }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
