name: Build, Scan and Push to ttl.sh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write  # Required for SARIF upload

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Generate image tag
        id: tag
        run: |
          SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=ttl.sh/jsonserver-operator-${SHA_SHORT}:24h" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          push: true
          tags: ${{ steps.tag.outputs.IMAGE_TAG }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.tag.outputs.IMAGE_TAG }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'  # Don't fail the build if vulnerabilities are found
          
      - name: Run Trivy for GitHub Security tab
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.tag.outputs.IMAGE_TAG }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
